name: lasitrade
description: "lasitrade"
publish_to: "none"

version: 1.5.5+56
date: "13 Jan, 2026"

environment:
  sdk: '>=3.6.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  provider: ^6.1.2
  get_it: ^8.0.1
  intl: ^0.20.2
  shared_preferences: ^2.3.2
  encrypted_shared_preferences: ^3.0.1
  collection: ^1.18.0
  path_provider: ^2.1.4
  dio: ^5.8.0+1
  logger: ^2.4.0
  web_socket_client: ^0.2.0
  window_manager: ^0.4.3
  fl_chart: ^1.1.1
  http: ^1.4.0
  webview_flutter: ^4.13.0 
  webview_flutter_wkwebview: ^3.23.5
  freezed_annotation: ^2.4.4
  postgres: ^3.5.6
  syncfusion_flutter_core: ^30.2.5
  syncfusion_flutter_datagrid: ^30.2.4
  syncfusion_flutter_sliders: ^30.2.6
  shadcn_flutter: 0.0.44
  financial_chart: ^0.4.0
  yaml: ^3.1.2
  flutter_dotenv: ^6.0.0
  hotkey_manager: ^0.2.3
  searchable_listview: ^2.19.3
  html: ^0.15.6
  url_launcher: ^6.3.2
  dotted_border: ^3.1.0
  csv: ^6.0.0
  table_calendar: ^3.2.0
  tray_manager: ^0.5.1
  app_links: ^6.3.3
  uuid: ^4.5.1
  timezone: ^0.9.2
  json_pretty: ^1.0.4
  audioplayers: ^6.5.1
  sentry_flutter: ^9.9.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.1
  build_runner: ^2.4.13

flutter_launcher_icons:
  image_path: 'assets/images/icon0.png' 
  ios: true
  remove_alpha_ios: true
  macos:
    generate: true
    # image_path: "assets/images/logo.png"
    image_path: "assets/images/app_icon_1024.png"

flutter:
  uses-material-design: true
  assets:
    - .env
    - pubspec.yaml
    - assets/fonts/
    - assets/images/
    - assets/data/
    - assets/sounds/
  fonts:
    - family: 'IBMPlexMono Regular'
      fonts:
        - asset: 'assets/fonts/IBMPlexMono/IBMPlexMono-Regular.ttf'
    - family: 'IBMPlexMono Light'
      fonts:
        - asset: 'assets/fonts/IBMPlexMono/IBMPlexMono-Light.ttf'
    # 
    - family: 'Ubuntu Regular'
      fonts:
        - asset: 'assets/fonts/Ubuntu/Ubuntu-Regular.ttf'
    - family: 'Ubuntu Light'
      fonts:
        - asset: 'assets/fonts/Ubuntu/Ubuntu-Light.ttf'

version0: 1.0.1+1
date0: "Apr 25, 2025"